### ISSUE TITLE
Fake quotes

### ISSUE THREAD

**Issue by rodorgas** [rodorgas/citadorbot#6]
The idea is to assign fake quotes to someone. For example: `/quote "I am increasingly convinced that the earth is flat" -photo "https://example.com/photo.png" -name "Caio Coppolla"`.

This may be used to damage people's reputation, but it may be used to make innocent funny jokes. I'm interested on what people would think of this feature, given the downsides. Obviously we want it to be used responsible, but we can't trust on everyone's intentions.
 
To mitigate harmful misuse, we may include a visual clue to indicate that this is a fake quote.

**Comment by Leandrigues** [comment]
Can this task be assigned to me?

**Comment by rodorgas** [comment]
The "visual clue" that indicates this is a fake quote could trace the quote back to the original author. For example, when user Fulano makes a fake quote, we could include "as described by @\Fulano".
