### ISSUE TITLE
Use some wrapper instead of spawning a shell process

### ISSUE THREAD

**Issue by rodorgas** [rodorgas/citadorbot#7]
Use some wrapper or library to renderize the images, like Pillow.

**Comment by luiz-meireles** [comment]
Parece que **[Wand](https://docs.wand-py.org/en/0.4.4/)** é uma bom  binding para o ImageMagick (https://stackoverflow.com/a/11658182/12854184)

**Comment by rodorgas** [comment]
Closed by #14, #15, #17.
