### ISSUE TITLE
Add context to quotes

### ISSUE THREAD

**Issue by wanderdasouza** [rodorgas/citadorbot#8]
I think it would be funny to leave a comment on the corner of a quote to give a context to it. This would be a great feature!

**Comment by caiotda** [comment]
i think this was already mentioned on issue #3

**Comment by rodorgas** [comment]
Thanks @wanderdasouza for raising the issue and @caiotda for pointing this is a duplicate. I will close this one, but @wanderdasouza you can react with 👍 on #3 to give it more visibility.
